#include "ui/StemWorkspaceComponent.h"
#include <array>
#include <cmath>
namespace jeff::daw { namespace { constexpr auto panel=0xff171d27; constexpr auto ink=0xffeef3fb; constexpr auto muted=0xff9aa8ba; constexpr auto accent=0xff5be7c4; }
TrackLaneComponent::TrackLaneComponent(juce::File f):source_(std::move(f)){name_.setText(source_.getFileNameWithoutExtension(),juce::dontSendNotification);name_.setColour(juce::Label::textColourId,juce::Colour(ink));name_.setFont(juce::FontOptions(15.0f,juce::Font::bold));name_.setTooltip(source_.getFullPathName());for(auto*c:std::array<juce::Component*,5>{&name_,&mute_,&solo_,&gain_,&pan_})addAndMakeVisible(*c);gain_.setRange(0,1.5,.01);gain_.setValue(1);gain_.setSliderStyle(juce::Slider::LinearHorizontal);gain_.setTextBoxStyle(juce::Slider::TextBoxRight,false,48,22);gain_.setName("Track gain");pan_.setRange(-1,1,.01);pan_.setSliderStyle(juce::Slider::LinearHorizontal);pan_.setTextBoxStyle(juce::Slider::TextBoxRight,false,48,22);pan_.setName("Track pan");mute_.setClickingTogglesState(true);solo_.setClickingTogglesState(true);}
void TrackLaneComponent::paint(juce::Graphics&g){auto r=getLocalBounds().toFloat().reduced(1);g.setColour(juce::Colour(panel));g.fillRoundedRectangle(r,8);auto w=r.withTrimmedLeft(250).withTrimmedRight(235).reduced(10,16);g.setColour(juce::Colour(0xff222d3b));g.fillRoundedRectangle(w,5);juce::Path p;auto seed=float(source_.getFileName().hashCode()&255)/255.0f;for(int x=0;x<int(w.getWidth());x+=4){auto a=(.12f+.72f*std::abs(std::sin(seed*8+x*.071f)))*w.getHeight()*.5f;auto px=w.getX()+float(x);if(x==0)p.startNewSubPath(px,w.getCentreY()-a);else p.lineTo(px,w.getCentreY()-a);p.lineTo(px,w.getCentreY()+a);}g.setColour(juce::Colour(accent).withAlpha(.78f));g.strokePath(p,juce::PathStrokeType(1.2f));g.setColour(juce::Colour(muted));g.setFont(11);g.drawText("PRESERVE · ORIGINAL MEDIA",12,43,218,20,juce::Justification::centredLeft);}
void TrackLaneComponent::resized(){auto r=getLocalBounds().reduced(10,8);auto l=r.removeFromLeft(225);name_.setBounds(l.removeFromTop(32));auto t=l.removeFromTop(28);mute_.setBounds(t.removeFromLeft(42));solo_.setBounds(t.removeFromLeft(42));auto m=r.removeFromRight(225);gain_.setBounds(m.removeFromTop(32));pan_.setBounds(m.removeFromTop(32));}
StemWorkspaceComponent::StemWorkspaceComponent(){heading_.setText("Stem Tracks",juce::dontSendNotification);heading_.setFont(juce::FontOptions(25,juce::Font::bold));heading_.setColour(juce::Label::textColourId,juce::Colour(ink));subheading_.setText("Drop Treblo stems here — preserve, blend, sync and export",juce::dontSendNotification);subheading_.setColour(juce::Label::textColourId,juce::Colour(muted));tempoLabel_.setText("PROJECT BPM",juce::dontSendNotification);tempoLabel_.setColour(juce::Label::textColourId,juce::Colour(muted));tempo_.setRange(40,240,.1);tempo_.setValue(120);tempo_.setSliderStyle(juce::Slider::LinearHorizontal);tempo_.setTextBoxStyle(juce::Slider::TextBoxRight,false,60,24);tempo_.setName("Project tempo BPM");timingMode_.addItem("Preserve",1);timingMode_.addItem("Edit",2);timingMode_.addItem("Auto Sync",3);timingMode_.setSelectedId(1);status_.setText("Add WAV, AIFF, FLAC or MP3 stems to begin.",juce::dontSendNotification);status_.setColour(juce::Label::textColourId,juce::Colour(muted));for(auto*c:std::array<juce::Component*,11>{&heading_,&subheading_,&addStems_,&play_,&autoSync_,&exportMix_,&saveProject_,&tempoLabel_,&tempo_,&timingMode_,&status_})addAndMakeVisible(*c);addStems_.onClick=[this]{chooseFiles();};play_.onClick=[this]{status_.setText("Playback activates after audio preparation is connected.",juce::dontSendNotification);};autoSync_.onClick=[this]{timingMode_.setSelectedId(3);status_.setText("Auto Sync proposal requires imported audio analysis.",juce::dontSendNotification);};exportMix_.onClick=[this]{status_.setText("Export engine is not connected yet; no file was written.",juce::dontSendNotification);};saveProject_.onClick=[this]{status_.setText("Project persistence is not connected yet; no file was written.",juce::dontSendNotification);};viewport_.setViewedComponent(&trackContent_,false);viewport_.setScrollBarsShown(true,false);addAndMakeVisible(viewport_);}
void StemWorkspaceComponent::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff0d1118));if(tracks_.isEmpty()){auto r=viewport_.getBounds().toFloat().reduced(24);g.setColour(juce::Colour(0xff17202b));g.fillRoundedRectangle(r,14);g.setColour(juce::Colour(accent));g.drawRoundedRectangle(r,14,1.5f);g.setFont(juce::FontOptions(20,juce::Font::bold));g.drawText("DROP STEM FILES HERE",r.toNearestInt().reduced(20),juce::Justification::centred);}}
void StemWorkspaceComponent::resized(){auto r=getLocalBounds().reduced(18);auto top=r.removeFromTop(62);heading_.setBounds(top.removeFromLeft(190));subheading_.setBounds(top);auto tools=r.removeFromTop(48);addStems_.setBounds(tools.removeFromLeft(118).reduced(2));play_.setBounds(tools.removeFromLeft(74).reduced(2));autoSync_.setBounds(tools.removeFromLeft(100).reduced(2));timingMode_.setBounds(tools.removeFromLeft(120).reduced(2));tempoLabel_.setBounds(tools.removeFromLeft(92).reduced(2));tempo_.setBounds(tools.removeFromLeft(180).reduced(2));saveProject_.setBounds(tools.removeFromRight(110).reduced(2));exportMix_.setBounds(tools.removeFromRight(104).reduced(2));status_.setBounds(r.removeFromBottom(28));viewport_.setBounds(r.reduced(0,8));relayoutTracks();}
bool StemWorkspaceComponent::supported(const juce::File&f){auto e=f.getFileExtension().toLowerCase();return e==".wav"||e==".aiff"||e==".aif"||e==".flac"||e==".mp3";}bool StemWorkspaceComponent::isInterestedInFileDrag(const juce::StringArray&f){for(auto&p:f)if(supported(juce::File(p)))return true;return false;}void StemWorkspaceComponent::filesDropped(const juce::StringArray&f,int,int){addFiles(f);}
void StemWorkspaceComponent::chooseFiles(){chooser_=std::make_unique<juce::FileChooser>("Add stem files",juce::File{},"*.wav;*.aiff;*.aif;*.flac;*.mp3");chooser_->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectMultipleItems,[safe=juce::Component::SafePointer<StemWorkspaceComponent>(this)](const juce::FileChooser&c){if(safe==nullptr)return;juce::StringArray paths;for(auto&f:c.getResults())paths.add(f.getFullPathName());safe->addFiles(paths);});}
void StemWorkspaceComponent::addFiles(const juce::StringArray&files){int added=0;for(auto&p:files){juce::File f(p);if(!f.existsAsFile()||!supported(f))continue;auto*lane=tracks_.add(new TrackLaneComponent(f));trackContent_.addAndMakeVisible(lane);++added;}status_.setText(added?juce::String(added)+" stem(s) staged in Preserve mode. Audio preparation is pending.":"No supported audio files were added.",juce::dontSendNotification);relayoutTracks();repaint();}
void StemWorkspaceComponent::relayoutTracks(){int width=juce::jmax(760,viewport_.getWidth()-viewport_.getScrollBarThickness()),row=92;trackContent_.setSize(width,juce::jmax(viewport_.getHeight(),tracks_.size()*row));for(int i=0;i<tracks_.size();++i)tracks_[i]->setBounds(0,i*row,width,row-6);}
}
